<?xml version="1.0"?>
<package format="3">
  <name>rosidl_core_runtime</name>
  <version>0.3.2</version>
  <description>C-only ROS interface runtime set for the Zephyr build.</description>
  <maintainer email="fj-blanco@users.noreply.github.com">Javier Blanco</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_export_depend>rosidl_runtime_c</build_export_depend>
  <build_export_depend>rosidl_typesupport_c</build_export_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
